# Generated by Django 4.1.5 on 2023-01-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="writer",
            field=models.CharField(
                default="미확인 사용자", max_length=32, verbose_name="작성자"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="content",
            field=models.TextField(verbose_name="내용"),
        ),
        migrations.AlterField(
            model_name="question",
            name="create_date",
            field=models.DateTimeField(verbose_name="작성일시"),
        ),
        migrations.AlterField(
            model_name="question",
            name="subject",
            field=models.CharField(max_length=200, verbose_name="제목"),
        ),
    ]
