# Generated by Django 4.1.5 on 2023-01-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0002_question_writer_alter_question_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="writer",
            field=models.CharField(default="", max_length=32, verbose_name="작성자"),
        ),
        migrations.AlterField(
            model_name="question",
            name="writer",
            field=models.CharField(default="", max_length=32, verbose_name="작성자"),
        ),
    ]
