"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--1+c(r=6k78jd8g!i4!6l+9!bb2hlc)1z^gntn03mzk3w7t%i+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
# 이 애플리케이션들은 일반적인 경우에 사용하기 편리하도록 기본 제공된다.
INSTALLED_APPS = [
    "pybo.apps.PyboConfig",
    # 관리용 사이트 ( 곧 사용 예정 )
    "django.contrib.admin",
    # 인증 시스템
    "django.contrib.auth",
    # 컨텐츠 타입을 위한 프레임워크
    "django.contrib.contenttypes",
    # 세션 프레임워크
    "django.contrib.sessions",
    # 메시징 프레임워크
    "django.contrib.messages",
    # 정적 파일을 관리하는 프레임워크
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# 어떻게 수정하지?
DATABASES = {
    # # 나는 sql을 연결하는 딕셔너리야
    # "default": {
    #     "ENGINE": "django.db.backends.sqlite3",
    #     "NAME": BASE_DIR / "db.sqlite3",
    # }

    # # 나는 오라클을 연동할거닷
    "default": {
        "ENGINE": "django.db.backends.oracle",
        "NAME" : "system",
        "USER" : "system",
        "PASSWORD" : "happyhappy1",
        "HOST" : "localhost",
        "PORT" : "1521",
    },
    # If you plan to run Django in a multithreaded environment ,
    # then you must set the threaded option of your Oracle database configuration to True:
    # 'OPTIONS': {
    #     'threaded': True,
    #     'use_returning_into': False,
    # },
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

# 한국어로 보여줘
LANGUAGE_CODE = "ko-kr"

# 시간은 한국 서울시간을 따를게
TIME_ZONE = "Asia/Seoul"

USE_I18N = True

# 기본값은 None, True로 두면 TIME_ZONE과 동일한 값이 들어가게 함
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
